function sim_caller_3D_171116_groundstate
% MI in 85/87 mixture
% Start in miscible 85-87 regime. Switch to waveguide, jump scattering
% length to negative value. Does MI still occur? Does the 85 form a 1D
% lattice which traps 87?


% File names
file_prefix     = '171116_groundstate';
groundstate     = [file_prefix,'_groundstate'];
data_out        = [file_prefix,'_data'];
pars_out        = [file_prefix,'_pars'];
overwrite_flag  = true;

% Set constants


%% SET PARAMETERS
% Set trap geoemtry, number, and grid discretisation. trap_shift is shift
% along z-axis.
pars    = struct(...
            'N_85',2e4,...
            'N_87',1.3e4,...
            'freq_x',50,...
            'freq_y',50,...
            'freq_z',7,...
            'freq_z_prop',0,...
            'trap_shift', 0,...
            'size_x',10e-6,...
            'size_y',10e-6,...
            'size_z',100e-6,...
            'n_x',128,...
            'n_y',128,...
            'n_z',512,...
            'gravityOn',true);

% Set scattering lengths 
pars    = appendfields(pars,...
            'RampTime',0,...
            'scat_init_85',50,...
            'scat_init_87',108,...
            'scat_init_8587',214,...
            'scat_prop_85',50,...
            'scat_prop_87',100,...
            'scat_prop_8587',214,...
            'scat_exp_85',-200,...
            'scat_exp_87',100,...
            'scat_exp_8587',214);

% Set three-body stuff
%3.3e-37
pars    = appendfields(pars,...
            'K3_re_init',0,...
            'K3_re_prop',0,...
            'K3_im_prop',-4.41e-41);

% Set sim time and step size
pars    = appendfields(pars,...
            'Tmax_real_init',10e-3,...
            'dt_real_init',0.1e-5,...
            'data_step_init',10,...
            'Tmax_real_prop',100e-3,...
            'dt_real_prop',0.5e-5,...
            'data_step_prop',1000);

% Set misc options
pars    = appendfields(pars,...
            'bdd_on',true,...
            'CUDA_flag', true,...
            'useLogScale',false,...           
            'saveImages',false,...
            'writeVideo',false);
        
        
% Set init/prop
pars    = appendfields(pars,...
            'propMode','init',...
            'initMode','torus',...
            'fileIn',groundstate,...
            'fileOut',data_out,...
            'overwriteFileIn',true);
        
% Set properties for pre-imaging expansion. expFactor_r, expFactor_z 
% indicate size of new array relative to original to be used for the
% expanded image.
pars    = appendfields(pars,...
            'ExpandOn',false,...
            'expFactor_r',3,...
            'expFactor_z',3,...
            'expTime',0e-3,...
            'expPostTime',0e-3,...
            'expPostStep',0e-3);
        
% Physical constants
pars    = appendfields(pars,...
            'hbar',1.0545718e-34,...
            'm85',1.4100e-25,...
            'm87',1.4432e-25,...
            'gDQS',9.7959938810,...
            'bohr_radius',5.2917721067e-11);
        
% Set noise properties
pars    = appendfields(pars,...
            'noiseFrac',0.1,...
            'noiseStdDevs',[4e-7,4e-7]);

        
% Save parameters to file
save(pars_out,'pars')

% a_85 s.t. 85-85 interaction is as strong as 85-87
a85_eqIntStr      = pars.m85/pars.m87*pars.scat_init_87;


% Get groundstate
pathIn              = '';
gsFile              =  [pathIn,sprintf('8587_groundstate_as=%4.1fa0',a85_eqIntStr)];
gsFile              = strrep(gsFile,'.','p');
pars.scat_init_85   = 50;%a85_eqIntStr;
pars.fileIn         = gsFile;
CQSSFM_8587_3D_sim(pars)

return
% Prop
aList   = [5];
nRunStart   = 7;
nRuns       = 12;
for i=1:numel(aList)
    aIn      = aList(i);
    for j=nRunStart:nRuns
        parsIn   = pars;
        propFile                =  [pathIn,sprintf('8587_waveguideProp_as=%4.1fa0_run%d',aIn,j)];
        propFile                  = strrep(propFile,'.','p');
        fprintf('Processing file %s . . . \n',propFile)
        parsIn.propMode         = 'prop';
        parsIn.scat_prop_85     = aIn;
        parsIn.fileOut          = propFile;
        
        CQSSFM_8587_sim(parsIn)
    end
end



end
